name: Reusable Build and Test Workflow
on: 
    workflow_call:
        inputs:
            python_version:
                description: Python version to use
                type: string
                required: true
            run_tests:
                description: Whether to run tests
                type: boolean
                required: true
                default: true
            lan:
                description: Runtime language
                type: string
        outputs:
            test_result:
                value: ${{ jobs.build-and-test.outputs.test-result }}
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            - name: Runtime Language
              run: |
                echo "Runtime language: ${{ inputs.lan }}"
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ inputs.python_version }}
            - name: Installing Dependencies
              run: pip install -r requirements.txt
            - name: Run tests
              id: test-result
              if: ${{ inputs.run_tests == true }}
              run: echo "Running Tests..."
            - name: Setting Test Result
              if: always()
              id: set-result
              run: |
                if [[ "${{steps.test-result.outcome}}" == "success" ]]; then
                    echo "result=passed" >> "$GITHUB_OUTPUT"
                else
                    echo "result=failed" >> "$GITHUB_OUTPUT"
                fi
        outputs: 
            test-result: ${{ steps.set-result.outputs.result }}     